routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('login/discord', 'Auth\LoginController@redirectToProvider')->name('login.discord');
Route::get('login/discord/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/', 'HomeController@index')->name('home');

// Profile Route
Route::prefix('p/{user}')->group(function () {
    Route::get('/', 'UserController@profile')->name('profile');
    Route::name('settings.')->prefix('settings')->group(function () {
        Route::get('/', 'UserController@settings')->name('index');
        Route::post('update/style', 'UserController@update_style')->name('update.style');
        Route::post('update/profile', 'UserController@update_profile')->name('update.profile');
        Route::post('update/password', 'UserController@update_password')->name('update.password');
        Route::post('update/avatar', 'UserController@update_avatar')->name('update.avatar');
    });
});

// Image Route
Route::post('/upload', 'ImageController@upload')->name('upload');

Route::prefix('/i/{image}')->group(function () {
    Route::get('/', 'ImageController@get')->name('image.show');

    Route::post('/updates', 'ImageController@infos')->name('image.infos');
    Route::get('/delete', 'ImageController@delete')->name('image.delete');
    Route::get('/download', 'ImageController@download')->name('image.download');
    Route::get('/{size}', 'ImageController@build');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'username';
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'email_verified_at', 'password', 'avatar',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function images()
    {
        return $this->hasMany('App\Image');
    }

    public function isSocialite()
    {
        return (! $this->password) ? true : false;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Image;
use App\Rules\MatchOldPassword;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Intervention\Image\Facades\Image as InterImage;

class UserController extends Controller
{
    public function profile(Request $request, $username)
    {
        $user = User::where('username', '=', $username)->firstOrFail();

        $userImages = Image::where('user_id', '=', $user->id)->orderBy('created_at', 'DESC')->paginate(18);

        return view('user.profile', [
            'user' => $user,
            'userImages' => $userImages,
        ]);
    }

    public function settings(Request $request, User $user)
    {
        abort_unless($user == $request->user(), 403);

        return view('user.settings', [
            'user' => $user,
        ]);
    }

    public function update_profile(Request $request, User $user)
    {
        abort_unless($user == $request->user(), 403);

        $user->always_public = $request->has('always_public');
        $user->description = $request->input('description');
        $user->save();

        notify()->success('You have successfully update your profile!');

        return back();
    }

    public function update_style(Request $request, User $user)
    {
        abort_unless($user == $request->user(), 403);

        $user->style = $request->has('style');
        $user->save();

        notify()->success('You have successfully update your style!');

        return back();
    }

    public function update_password(Request $request)
    {
        $request->validate([
            'current_password' => ['required', new MatchOldPassword],
            'new_password' => ['required', 'string', 'min:8'],
            'new_confirm_password' => ['same:new_password'],
        ]);

        User::find(auth()->user()->id)->update(['password' => Hash::make($request->new_password)]);

        notify()->success('You have successfully update your passsword.');

        return back();
    }

    public function update_avatar(Request $request, User $user)
    {
        abort_unless($user == $request->user(), 403);

        $rules = [
            'avatar' => 'required | mimes:jpeg,jpg,png,gif,bmp,tiff',
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            notify()->error('Image must be filled!');

            return back();
        }

        $user = auth()->user();

        $avatar = $request->file('avatar');

        $maxSize = 2000000; // 2 MB

        if ($maxSize >= $avatar->getSize()) {
            $avatarName = strtolower($user->username).'.'.$request->file('avatar')->getClientOriginalExtension();
            $location = storage_path('app/public/avatars/'.$avatarName);

            $oldExt = pathinfo($user->avatar, PATHINFO_EXTENSION);
            $oldAvatar = storage_path('app/public/avatars/'.strtolower($user->username).'.'.$oldExt);

            if (file_exists($oldAvatar)) {
                File::delete($oldAvatar);
            }

            if ($avatar->getClientOriginalExtension() == 'gif') {
                copy($avatar->getRealPath(), $location);
            } else {
                InterImage::make($avatar)->resize(150, 150)->save($location);
            }
        } else {
            notify()->error('Your avatar is too large, max file size: 2 MB');

            return back();
        }

        $user->avatar = 'avatars/'.$avatarName;
        $user->save();

        notify()->success('You have successfully upload avatar.');

        return back();
    }
}

resources/views/user/profile.blade.php
@extends('layouts.app')

@section('head')
<title>{{ $user->username }}'s profile — {{ config('app.name', 'Laravel') }} — {{ config('app.description') }}</title>

<!-- OpenGraph/Twitter -->
<meta data-rh="true" name="description" content="{{ $user->username }}'s Profile" />
<meta data-rh="true" property="og:url" content="{{ url()->current() }}" />
<meta data-rh="true" property="og:description" content="{{ $user->username }}'s Profile" />
<meta data-rh="true" property="og:image" content="{{ url(Storage::url($user->avatar)) }}" />
<meta data-rh="true" property="og:title" content="{{ config('app.name') }}" />
<meta data-rh="true" property="og:website" content="website" />
<meta data-rh="true" property="og:site_name" content="{{ config('app.name') }}.app" />
<meta data-rh="true" name="twitter:image:src" content="{{ url(Storage::url($user->avatar)) }}" />
<meta data-rh="true" property="twitter:description" content="{{ $user->username }}'s Profile" />
<meta data-rh="true" name="twitter:card" content="summary_large_image" />
<meta data-rh="true" name="twitter:creator" content="@HavensYT" />
<meta data-rh="true" name="author" content="Thomas Drumont" />
<meta data-rh="true" name="twitter:site" content="@limg_app" />
<meta data-rh="true" property="twitter:title" content="{{ config('app.name') }}" />
@endsection

@section('content')

<div class="px-8 pt-6 pb-8 mx-4 bg-white rounded-lg shadow-md dark:bg-midnight sm:container sm:mx-auto sm:w-full">
    <div class="sm:px-2">
        <div class="sm:-mx-2 sm:flex">
            <div class="sm:w-1/3 sm:px-2">
                <div class="flex sm:ml-0 md:ml-1 lg:ml-4 xl:ml-40">
                    <img class="w-24 rounded sm:w-38" src="{{ Storage::url($user->avatar) }}"/>
                    <div class="mt-4 ml-2 sm:ml-4">
                        <h4 class="text-lg sm:text-5xl font-firacode dark:text-gray-300">{{ $user->username }}</h4>
                        <p class="text-sm sm:text-xl dark:text-gray-300 font-firacode"><span class="text-green-600">{{ $user->images->count() }}</span> Images</p>
                    </div>
                </div>  
            </div>
            <div class="sm:w-1/3 sm:px-2">
                <div class="mt-4 sm:ml-24 sm:mt-10">
                    @if (Auth::check() && auth()->user()->id == $user->id)
                    <form action="{{ route('settings.update.profile', ['user' => $user]) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <input name="description" value="{{ $user->description }}" placeholder="Description" class="w-4/6 px-3 py-2 text-gray-800 border rounded shadow appearance-none sm:w-3/5">
                        <button type="submit" class="inline-flex items-center px-2 py-2 font-bold text-white bg-indigo-700 border-2 border-indigo-700 rounded shadow-md hover:border-indigo-600 hover:bg-indigo-800 hover:text-white">
                            <i class="mr-2 fas fa-save"></i> Save
                        </button>
                    </form>
                    @elseif ($user->description)
                    <h4 class="text-lg sm:text-xl font-firacode dark:text-gray-300" title="Description">{{ $user->description }}</h4>
                    @else
                    <h1 class="text-lg sm:text-xl font-firacode dark:text-gray-300">This user has no description</h1>
                    @endif
                    <h4 class="text-lg sm:text-xl font-firacode dark:text-gray-300" title="Registration date">{{ $user->created_at === null ? "N/A" : date('M d Y', $user->created_at->getTimestamp()) }}</h4>
                </div>
            </div>
            <div class="sm:w-1/3 sm:px-2">
                <div class="mt-4 sm:ml-24 sm:mt-10">
                    @if (Auth::check() && auth()->user()->id == $user->id)
                    <form action="{{ route('settings.update.profile', ['user' => $user]) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <label for="always_public" class="flex items-center justify-center pt-6 pb-3 pr-3 cursor-pointer">
                        <div class="relative">
                            <input name="always_public" id="always_public" type="checkbox" class="hidden" value="{{ $user->always_public ? '1' : '0' }}" {{ $user->always_public ? 'checked' : '' }} onChange="form.submit()"/>
                            <div class="w-10 h-4 bg-gray-400 rounded-full shadow-inner toggle__line"></div>
                            <div class="absolute inset-y-0 left-0 w-6 h-6 bg-white rounded-full shadow toggle__dot"></div>
                        </div>
                        <span class="pl-4 font-bold text-gray-800 dark:text-gray-300">Always Upload Image in public</span>
                        </label>
                    </form>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>     
<br class="my-10">
<div class="px-8 pt-6 pb-8 mx-4 bg-white rounded-lg shadow-md dark:bg-midnight sm:container sm:mx-auto sm:w-full">
    @if ($user->images->count() != 0)
    <div data-controller="tabs" data-tabs-active-tab="-text-gray-600 border-b-2 border-blue-500 text-blue-500" class="pb-6">
        <ul class="flex flex-col list-reset sm:flex-row">
            <li data-target="tabs.tab" data-action="click->tabs#change">
                <a href="#all" class="block px-6 py-4 font-medium text-center dark:text-gray-300 focus:outline-none">
                    <i class="fas fa-globe"></i> All
                </a>
            </li>
            @if (Auth::check() && auth()->user()->id == $user->id)
            <li data-target="tabs.tab" data-action="click->tabs#change">
                <a href="#public" class="block px-6 py-4 text-center dark:text-gray-300 focus:outline-none">
                    <i class="fas fa-globe-europe"></i> Public
                </a>
            </li>
            <li data-target="tabs.tab" data-action="click->tabs#change">
                <a href="#private" class="block px-6 py-4 text-center dark:text-gray-300 focus:outline-none">
                    <i class="fas fa-user-lock"></i> Private
                </a>
            </li>
            @endif
        </ul>
        <div class="hidden px-4 py-4" data-target="tabs.panel">
            <div class="flex flex-wrap">
                @foreach ($userImages as $image)
                    @isNotPublic($image)
                    @else
                    <div class="p-3 md:w-1/2 lg:w-1/6">
                        <a href="{{ route('image.show', ['image' => $image->name]) }}" class="block h-56 overflow-hidden rounded-lg sm:shadow-lg">
                            <h1 class="items-center justify-between h-16 p-3 px-4 text-lg leading-tight bg-white rounded-t dark:text-gray-300 dark:bg-forest lg:flex">{{ $image->title ?? '‌‌' }} <small class="dark:text-gray-400">@if($image->is_public) Public @else Private @endif</small></h1>
                            <img class="w-full rounded-b" src="{{ route('image.show', ['image' => $image->fullname]) }}" alt="{{ $image->title ?? $user->username }}">
                        </a>
                    </div>
                    @endisNotPublic
                @endforeach
            </div>
            <div class="pt-5 text-center">
                {{ $userImages->links() }}
            </div>
        </div>
        @if (Auth::check() && auth()->user()->id == $user->id)
        <div class="hidden px-4 py-4" data-target="tabs.panel">
            <div class="flex flex-wrap">
                @foreach ($user->images as $image)
                    @if ($image->is_public)
                    <div class="p-3 md:w-1/2 lg:w-1/6">
                        <a href="{{ route('image.show', ['image' => $image->name]) }}" class="block h-56 overflow-hidden rounded-lg sm:shadow-lg">
                            <h1 class="items-center justify-between h-16 p-3 px-4 text-lg leading-tight bg-white rounded-t dark:text-gray-300 dark:bg-forest lg:flex">{{ $image->title ?? '‌‌' }} <small class="dark:text-gray-400">@if($image->is_public) Public @else Private @endif</small></h1>
                            <img class="w-full rounded-b" src="{{ route('image.show', ['image' => $image->fullname]) }}" alt="{{ $image->title ?? $user->username }}">
                        </a>
                    </div>
                    @endif
                @endforeach
            </div>
        </div>
        <div class="hidden px-4 py-4" data-target="tabs.panel">
            <div class="flex flex-wrap">
                @foreach ($user->images as $image)
                    @if (!$image->is_public)
                    <div class="p-3 md:w-1/2 lg:w-1/6">
                        <a href="{{ route('image.show', ['image' => $image->name]) }}" class="block h-56 overflow-hidden rounded-lg sm:shadow-lg">
                            <h1 class="items-center justify-between h-16 p-3 px-4 text-lg leading-tight bg-white rounded-t dark:text-gray-300 dark:bg-forest lg:flex">{{ $image->title ?? '‌‌' }} <small class="dark:text-gray-400">@if($image->is_public) Public @else Private @endif</small></h1>
                            <img class="w-full rounded-b" src="{{ route('image.show', ['image' => $image->fullname]) }}" alt="{{ $image->title ?? $user->username }}">
                        </a>
                    </div>
                    @endif
                @endforeach
            </div>
        </div>
        @endif
    </div>
    @else
        <div class="py-4 text-center lg:px-4">
            <div class="flex items-center p-2 leading-none text-indigo-100 bg-indigo-800 lg:rounded-full lg:inline-flex" role="alert">
                <span class="flex px-2 py-1 mr-3 text-xs font-bold uppercase bg-indigo-500 rounded-full">Info</span>
                <span class="flex-auto mr-2 font-semibold text-left">This user has no image</span>
            </div>
        </div>
    @endif
</div>

@endsection

resources/views/user/settings.blade.php
@extends('layouts.app')

@section('head')
<title>{{ $user->username }}'s settings — {{ config('app.name', 'Laravel') }} — {{ config('app.description') }}</title>

<!-- OpenGraph/Twitter -->
<meta data-rh="true" name="description" content="{{ $user->username }}'s Settings" />
<meta data-rh="true" property="og:url" content="{{ url()->current() }}" />
<meta data-rh="true" property="og:description" content="{{ $user->username }}'s Settings" />
<meta data-rh="true" property="og:image" content="{{ url(Storage::url($user->avatar)) }}" />
<meta data-rh="true" property="og:title" content="{{ config('app.name') }}" />
<meta data-rh="true" property="og:website" content="website" />
<meta data-rh="true" property="og:site_name" content="{{ config('app.name') }}.app" />
<meta data-rh="true" name="twitter:image:src" content="{{ url(Storage::url($user->avatar)) }}" />
<meta data-rh="true" property="twitter:description" content="{{ $user->username }}'s Settings" />
<meta data-rh="true" name="twitter:card" content="summary_large_image" />
<meta data-rh="true" name="twitter:creator" content="@HavensYT" />
<meta data-rh="true" name="author" content="Thomas Drumont" />
<meta data-rh="true" name="twitter:site" content="@limg_app" />
<meta data-rh="true" property="twitter:title" content="{{ config('app.name') }}" />

@endsection

@section('content')
<div class="container mx-auto mt-10">
  @if (auth()->user() == $user)
  <div class="max-w-lg px-8 pt-6 pb-8 mx-4 bg-white rounded-lg shadow-md dark:bg-midnight sm:container sm:mx-auto sm:w-full">
    <div class="flex items-center justify-center mb-8">
      <img class="ml-12 rounded-lg shadow-md sm:ml-14 w-38" src="{{ Storage::url($user->avatar) }}" alt="{{ $user->username }}">
      <form action="{{ route('settings.update.avatar', ['user' => $user]) }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="relative w-32 mx-2 my-4 ml-6 overflow-hidden sm:ml-12 sm:mx-10">
          <label id="image-drop" class="inline-flex items-center w-24 py-2 pr-2 font-bold text-white bg-indigo-700 rounded-lg cursor-pointer hover:bg-indigo-800 sm:px-4 sm:w-full" for="avatar-upload">
            <div class="ml-2">
              <i class="fas fa-file-import"></i> Upload
            </div>
            <input class="hidden opacity-0 sm:absolute sm:-ml-4 sm:h-10 sm:w-32 sm:block" id="avatar-upload" type="file" name="avatar" aria-describedby="avatar" onChange="form.submit()">
          </label>
        </div>
      </form>
    </div>
    <div class="sm:hidden">
    <hr>
      <form action="{{ route('settings.update.style', ['user' => $user]) }}" method="POST" enctype="multipart/form-data">
          @csrf
          <label for="style" class="flex items-center justify-center pt-3 pb-3 pr-3 cursor-pointer">
          <div class="relative">
              <input name="style" id="style" type="checkbox" class="hidden" value="{{ $user->style ? '1' : '0' }}" {{ $user->style ? 'checked' : '' }} onChange="form.submit()"/>
              <div class="w-10 h-4 bg-gray-400 rounded-full shadow-inner toggle__line"></div>
              <div class="absolute inset-y-0 left-0 w-6 h-6 bg-white rounded-full shadow toggle__dot"></div>
          </div>
          <span class="pl-4 font-bold text-white dark:text-gray-300">Style</span>
          </label>
      </form>
    </div>
    <hr class="pb-4">
    @if(!auth()->user()->isSocialite())
    <form method="POST" action="{{ route('settings.update.password', ['user' => $user]) }}">
      @csrf
      <div class="flex flex-wrap mb-6 -mx-3">
        <div class="w-full px-3">
          <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase dark:text-gray-400" for="password">
            {{ __('Current Password') }}
          </label>
          <input class="block w-full px-4 py-3 mb-3 leading-tight text-gray-700 bg-gray-200 border border-gray-200 rounded appearance-none focus:outline-none focus:bg-white focus:border-gray-500" 
          placeholder="******************" id="password" type="password" name="current_password" autocomplete="current-password" @if($errors->all())value="{{ old('current_password') }}" @endif>
        </div>
      </div>
      <div class="flex flex-wrap -mx-3 @if(!$errors->all())mb-4 @endif">
        <div class="w-full px-3 mb-6 md:w-1/2 md:mb-0">
          <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase dark:text-gray-400" for="password">
            {{ __('New Password') }}
          </label>
          <input class="appearance-none block w-full bg-gray-200 text-gray-700 border @if($errors->all()) border-red-500 @endif rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" 
          placeholder="******************" id="new_password" type="password" name="new_password" autocomplete="current-password">
        </div>
        <div class="w-full px-3 md:w-1/2">
          <label class="block mb-2 text-xs font-bold tracking-wide text-gray-700 uppercase dark:text-gray-400" for="password">
            {{ __('New Confirm Password') }}
          </label>
          <input class="block w-full px-4 py-3 leading-tight text-gray-700 bg-gray-200 border border-gray-200 rounded appearance-none focus:outline-none focus:bg-white focus:border-gray-500" 
          placeholder="******************" id="new_confirm_password" type="password" name="new_confirm_password" autocomplete="current-password">
        </div>
      </div>
      @if ($errors->all())
        <div class="flex items-center mb-4">
          @foreach ($errors->all() as $error)
            <p class="text-xs italic text-red-500">{{ $error }}</p>
          @endforeach 
        </div>
      @endif
      <div class="md:flex md:items-center">
        <div class="md:w-1/3">
        <button class="inline-flex items-center px-5 py-2 font-bold text-white bg-indigo-700 border-b-2 border-indigo-500 rounded shadow-md hover:border-indigo-600 hover:bg-indigo-800 hover:text-white">
          <i class="mr-2 fas fa-save"></i> Save
        </button>
        </div>
        <div class="md:w-2/3"></div>
      </div>
    </form>
    @else 
    <div class="flex">
      <i class="text-center text-gray-600">Because you signed in with Discord you have no password options.</i>
    </div>
    @endif
  </div>
  @endif
</div>
@endsection