routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('login/discord', 'Auth\LoginController@redirectToProvider')->name('login.discord');
Route::get('login/discord/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/', 'HomeController@index')->name('home');

// Profile Route
Route::prefix('p/{user}')->group(function () {
    Route::get('/', 'UserController@profile')->name('profile');
    Route::name('settings.')->prefix('settings')->group(function () {
        Route::get('/', 'UserController@settings')->name('index');
        Route::post('update/style', 'UserController@update_style')->name('update.style');
        Route::post('update/profile', 'UserController@update_profile')->name('update.profile');
        Route::post('update/password', 'UserController@update_password')->name('update.password');
        Route::post('update/avatar', 'UserController@update_avatar')->name('update.avatar');
    });
});

// Image Route
Route::post('/upload', 'ImageController@upload')->name('upload');

Route::prefix('/i/{image}')->group(function () {
    Route::get('/', 'ImageController@get')->name('image.show');

    Route::post('/updates', 'ImageController@infos')->name('image.infos');
    Route::get('/delete', 'ImageController@delete')->name('image.delete');
    Route::get('/download', 'ImageController@download')->name('image.download');
    Route::get('/{size}', 'ImageController@build');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="h-full @guest mode-dark @endguest @auth @if ($user->style == 1) mode-dark @endif @endauth">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Title & Meta -->
    @section('head')
    <title>{{ config('app.name', 'Laravel') }} — {{ config('app.description') }}</title>

    <!-- OpenGraph/Twitter -->
    <meta data-rh="true" name="description" content="{{ config('app.description') }}" />
    <meta data-rh="true" property="og:url" content="{{ url()->current() }}" />
    <meta data-rh="true" property="og:description" content="{{ config('app.description') }}" />
    <meta data-rh="true" property="og:image" content="{{ asset('images/cover.png') }}" />
    <meta data-rh="true" property="og:title" content="{{ config('app.name') }}" />
    <meta data-rh="true" property="og:website" content="website" />
    <meta data-rh="true" property="og:site_name" content="{{ config('app.name') }}.app" />
    <meta data-rh="true" name="twitter:image:src" content="{{ asset('images/cover.png') }}" />
    <meta data-rh="true" property="twitter:description" content="{{ config('app.description') }}" />
    <meta data-rh="true" name="twitter:card" content="summary_large_image" />
    <meta data-rh="true" name="twitter:creator" content="@HavensYT" />
    <meta data-rh="true" name="author" content="Thomas Drumont" />
    <meta data-rh="true" name="twitter:site" content="@limg_app" />
    <meta data-rh="true" property="twitter:title" content="{{ config('app.name') }}" />
    @show


    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png">
    <link rel="manifest" href="/images/favicon/site.webmanifest">
    <link rel="mask-icon" href="/images/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="/images/favicon/favicon.ico">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="/images/favicon/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">

    <!-- Styles -->
    <link rel="stylesheet" type="text/css" href="{{ asset('css/app.css') }}">

</head>

<body class="flex flex-col h-full">

<header class="dark:shadow-lg navbar dark:bg-midnight">
    @include('layouts.navbar')
</header>
<div id="content" class="flex-1 w-full p-3 bg-gray-100 dark:bg-asphalt sm:p-8">
    @yield('content')
</div> 
@include('layouts.footer')

<!-- Scripts -->
@include('notify::messages')
@include('sweetalert::alert')
@yield('javascripts')
<script type="text/javascript" src="{{ mix('js/app.js') }}"></script>
<script type="module" src="{{ mix('js/instantpage.js') }}" defer></script>

</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="w-full p-4 text-center text-gray-800 shadow-md dark:bg-midnight dark:text-white font-firacode">
  <i class="far fa-heart"></i> <a href="https://github.com/havenstd06/limg" target="_nofollow">LIMG</a> {{ date('Y') }}
</footer>

resources/views/layouts/navbar.blade.php
<div class="container px-4 mx-auto">
    <div class="flex items-center justify-center py-6 sm:justify-between sm:py-4">
        <div class="flex">
            <a href="{{ route('home') }}">
                <img src="{{ url('images/logo-text-min-p.png') }}" alt="{{ config('app.name') }} Logo" class="h-10 rounded-lg">
            </a>
            <form action="{{ route('upload') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <label id="image-drop"
                class="flex items-center px-2 py-2 ml-3 -mt-1 text-purple-700 bg-white border border-purple-800 rounded-lg shadow-lg hover:bg-purple-600 hover:text-white dark-hover:bg-purple-600 dark-hover:text-white" for="image-upload">
                    <i class="ml-1 far fa-file-image"></i>
                    <span class="ml-1 leading-normal text-center">
                        <strong>Upload</strong>
                    </span>
                    <input class="hidden opacity-0 sm:absolute sm:-ml-3 sm:-mt-15 sm:h-12 sm:w-27 sm:block" id="image-upload" type="file" accept="image/*" name="image" aria-describedby="image" onChange="form.submit()"/>
                </label>
            </form>
        </div>
        @guest
        <div class="hidden sm:flex sm:items-center">
            <a href="{{ route('login') }}" class="mr-4 text-sm font-semibold text-gray-800 hover:text-purple-600 dark:text-gray-200 dark-hover:text-purple-600">{{ __('Login') }}</a>
            <a href="{{ route('register') }}" class="px-4 py-2 text-sm font-semibold text-gray-800 border rounded-lg hover:text-purple-600 hover:border-purple-600 dark:text-gray-200 dark-hover:text-purple-600">{{ __('Register') }}</a>
        </div>
        @else
        <div class="hidden sm:flex sm:items-right">
            <form action="{{ route('settings.update.style', ['user' => $user]) }}" method="POST" enctype="multipart/form-data">
                @csrf
                <label for="style" class="flex items-center justify-center pt-3 pr-3 cursor-pointer">
                <div class="relative">
                    <input name="style" id="style" type="checkbox" class="hidden" value="{{ $user->style ? '1' : '0' }}" {{ $user->style ? 'checked' : '' }} onChange="form.submit()"/>
                    <div class="w-10 h-4 bg-gray-400 rounded-full shadow-inner toggle__line"></div>
                    <div class="absolute inset-y-0 left-0 w-6 h-6 bg-white rounded-full shadow toggle__dot"></div>
                </div>
                </label>
            </form>
            <div class="relative leading-none no-underline rounded" data-controller="dropdown">
                <div data-action="click->dropdown#toggle click@window->dropdown#hide" role="button" class="inline-block select-none">
                    <button class="inline-flex items-center px-4 py-1 font-semibold text-gray-700 rounded dark:text-white">
                        <img src="{{ Storage::url(auth()->user()->avatar) }}" class="inline-block w-10 mr-2 -mt-1 -mb-1 -ml-1 border-white border-solid rounded shadow-md">		
                            {{ auth()->user()->username }}
                        <svg class="w-4 h-4 -mr-1 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/> </svg>
                    </button>
                </div>
                <div data-target="dropdown.menu" class="absolute right-0 hidden mt-2">
                <div class="w-40 overflow-hidden bg-white border rounded shadow">
                    <a href="{{ route('profile', auth()->user()->username) }}" class="block py-3 pl-8 text-gray-800 no-underline whitespace-no-wrap bg-white hover:bg-gray-300 dark-hover:bg-gray-300">
                        <i class="fas fa-user"></i> {{ __('Profile') }}
                    </a>
                    <a href="{{ route('settings.index', ['user' => $user]) }}" class="block py-3 pl-8 text-gray-800 no-underline whitespace-no-wrap bg-white hover:bg-gray-300 dark-hover:bg-gray-300">
                        <i class="fas fa-cogs"></i> {{ __('Settings') }}
                    </a>
                    <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="block py-3 pl-8 text-gray-800 no-underline whitespace-no-wrap bg-white border-t hover:bg-gray-300 dark-hover:bg-gray-300">
                        <i class="fas fa-sign-out-alt"></i> {{ __('Logout') }}
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="hidden">
                        @csrf
                    </form>
                </div>
                </div>
            </div>
        </div>
        @endguest
    </div>
    <div class="block py-2 bg-white border-t-2 dark:bg-midnight sm:hidden">
        <div class="flex flex-col">
            @guest
            <div class="flex items-center justify-between pt-2">
                <a href="{{ route('login') }}" class="ml-3 mr-4 text-sm font-semibold text-gray-800 hover:text-purple-600 dark:text-gray-200 dark-hover:text-purple-600">{{ __('Login') }}</a>
                <a href="{{ route('register') }}" class="px-4 py-1 mr-3 text-sm font-semibold text-gray-800 border rounded-lg hover:text-purple-600 hover:border-purple-600 dark:text-gray-200 dark-hover:text-purple-600">{{ __('Register') }}</a>
            </div>
            @else 
            <div class="block py-2 bg-white rounded dark:bg-asphalt sm:hidden">
                <div class="flex items-center justify-center">
                    <img src="{{ Storage::url($user->avatar) }}" class="inline-block w-10 mr-4 border-white border-solid rounded-lg">
                    <a href="{{ route('profile', auth()->user()->username) }}" class="mr-4 text-sm font-semibold text-gray-800 dark:text-gray-300 hover:text-purple-600">
                        <i class="fas fa-user"></i> {{ __('Profile') }}
                    </a>
                    <a href="{{ route('settings.index', ['user' => $user]) }}" class="mr-4 text-sm font-semibold text-gray-800 dark:text-gray-300 hover:text-purple-600">
                        <i class="fas fa-cogs"></i> {{ __('Settings') }}
                    </a>
                    <a href="{{ route('logout') }}" class="mr-4 text-sm font-semibold text-gray-800 dark:text-gray-300 hover:text-purple-600"
                    onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                        <i class="fas fa-sign-out-alt"></i> {{ __('Logout') }}
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="hidden">
                        @csrf
                    </form>
                </div>
            </div>
            @endguest
        </div>
    </div>
</div>

@section('javascripts')
<script>
    var fileInput = document.querySelector('input[type=file]');
    var dropzone = document.querySelector('label#image-drop');

    fileInput.addEventListener('dragenter', function () {
    dropzone.classList.remove('text-purple-700', 'bg-white');
    dropzone.classList.add('text-white', 'bg-purple-600');
    });

    fileInput.addEventListener('dragleave', function () {
    dropzone.classList.remove('text-white', 'bg-purple-600');
    dropzone.classList.add('text-purple-700', 'bg-white');
    });
</script>
@endsection